### ISSUE TITLE
Security Example configuration is old

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-graphql#282]
### Issue description

see: https://github.com/micronaut-projects/micronaut-graphql/blob/master/examples/jwt-security/src/main/resources/application.yml

I think this

```yaml
micronaut:
  security:
    enabled: true
    authentication: cookie
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
      refresh:
        cookie:
          enabled: false
    intercept-url-map:
      - pattern: /**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /**
        http-method: POST
        access:
          - isAnonymous()
graphql:
  graphiql.enabled: true
```

can be : 

```yaml
micronaut:
  security:
    authentication: cookie
    token:
      refresh:
        cookie:
          enabled: false
    intercept-url-map:
      - pattern: /**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /**
        http-method: POST
        access:
          - isAnonymous()
graphql:
  graphiql.enabled: true
```
